# Generated by Django 3.2.15 on 2023-12-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id2', models.IntegerField()),
                ('researcher', models.CharField(max_length=50)),
                ('num_target_patients', models.IntegerField()),
                ('num_recorded_patients', models.IntegerField()),
                ('num_target_samples', models.IntegerField()),
                ('num_samples_collected', models.IntegerField()),
            ],
        ),
    ]
