# Generated by Django 3.2.15 on 2023-12-28 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='study',
            old_name='id2',
            new_name='identification',
        ),
    ]
